# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    binary: asc

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

brews:
  -
    name: asc
    goarm: 6
    goamd64: v1
    url_template: "https://github.com/harleymckenzie/asc/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    homepage: "https://github.com/harleymckenzie/asc"

    # Git author used to commit to the repository.
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com

    # The project name and current git tag are used in the format string.
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"

    # Directory inside the repository to put the formula.
    directory: Formula
    description: "AWS Simple CLI (ASC) - A simplified interface for AWS operations."
    license: "MIT"
    skip_upload: false

    test: |
      system "#{bin}/asc help"

    install: |
      bin.install "asc"

    extra_install: |
      generate_completions_from_executable(bin/"asc", "completion", shells: [:bash, :zsh, :fish])

    # Repository to push the generated files to.
    repository:
      owner: harleymckenzie
      name: homebrew-asc
      pull_request:
        enabled: true
        draft: true
        base:
          owner: harleymckenzie
          name: homebrew-asc
          branch: main
