# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AscGo < Formula
  desc "AWS CLI tool for managing AWS resources."
  homepage "https://github.com/harleymckenzie/asc-go"
  version "1.1.1"
  license "MIT"

  depends_on "go" => :build
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/harleymckenzie/asc-go/releases/download/v1.1.1/asc-go_Darwin_x86_64.tar.gz"
    sha256 "03af5840bf868615a9d240273f34afb29ee7145e0305ac546167326f065a73b1"

    def install
      ENV["GOPATH"] = buildpath
      system "go", "build", "-v", "-o", bin/"asc"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/harleymckenzie/asc-go/releases/download/v1.1.1/asc-go_Darwin_arm64.tar.gz"
    sha256 "fc2ff4c409ee018457ef0c93cd69d0bf8c58dd207a052a1400243ba12527c8c6"

    def install
      ENV["GOPATH"] = buildpath
      system "go", "build", "-v", "-o", bin/"asc"
    end
  end

  test do
    system "#{bin}/asc help"
  end
end
