name: Create Release

on:
  push:
    branches:    
      - dev
    tags:        
      - v*

jobs:
  create-release:
    # Set release tag to the tag name
    name: "Create Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: "write"
      pull-requests: "write"
      repository-projects: "write"
    steps:
      - run: echo "Creating release for tag ${{ github.ref }}"
      - name: Create release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "${{ github.ref }}"
          title: "Release ${{ github.ref }}"
