name: Increment Version
concurrency: automated-release
on:
  push:
    branches:
      - dev
jobs:
  create_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump version and push tag
        id: create_tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
          WITH_V: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update setup.py version
        run: |
          NEW_VERSION=${{ steps.create_tag.outputs.tag }} # This will include the 'v' at the start
          # Strip the 'v' from the version
          NEW_VERSION=${NEW_VERSION#v}
          sed -i "s/version='.*'/version='${NEW_VERSION}'/" setup.py
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add setup.py
          git commit -m "Update setup.py version to ${NEW_VERSION}"
          git push

      - name: Trigger Release Workflow
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/harleymckenzie/asc/dispatches \
          -d '{"event_type": "trigger-release-workflow", "client_payload": {"version": "${{ steps.create_tag.outputs.tag }}"}}'